<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../../../public/css/style.css">
</head>
<body>
<div class="container-error">
    <div class="error-template">
        <h1>Oops!</h1>
        <h2>404 Not Found</h2>
        <div class="error-details">
            Sorry, an error has occured, Requested page not found!<br>
        </div>
    </div>
</div>
</body>
</html>
